In [ ]:
import numpy as np
import h5py

In [ ]:
hf = h5py.File('SingleElectronPt50_IMGCROPS_n249k_RHv1.hdf5', 'r')
hf1 = h5py.File('SinglePhotonPt50_IMGCROPS_n249k_RHv1.hdf5', 'r')

In [ ]:
print(hf.keys())
print(hf1.keys())

<KeysViewHDF5 ['X', 'y']>
<KeysViewHDF5 ['X', 'y']>


In [ ]:
#For electrons
e_X = hf.get('X')
print(e_X)
e_y = hf.get('y')
print(e_y)

#for protons
p_X = hf1.get('X')
print(p_X)
p_y = hf1.get('y')
print(p_y)

<HDF5 dataset "X": shape (249000, 32, 32, 2), type "<f4">
<HDF5 dataset "y": shape (249000,), type "<f4">
<HDF5 dataset "X": shape (249000, 32, 32, 2), type "<f4">
<HDF5 dataset "y": shape (249000,), type "<f4">


In [ ]:
e_X = np.array(e_X)
print(e_X.shape)
e_y = np.array(e_y)
print(e_y.shape)

p_X = np.array(p_X)
print(p_X.shape)
p_y = np.array(p_y)
print(p_y.shape)

(249000, 32, 32, 2)
(249000,)
(249000, 32, 32, 2)
(249000,)


In [ ]:
hf.close()
hf1.close()

In [ ]:
e_train = []
p_train = []
e_val = []
p_val = []
e_test = []
p_test = []
for i in range(0,199200):
  e_train.append(e_X[i])
  p_train.append(p_X[i])

for j in range(199200, 224100):
  e_val.append(e_X[j])
  p_val.append(p_X[j])

for k in range(224100, 249000):
  e_test.append(e_X[k])
  p_test.append(p_X[k])

In [ ]:
X_train = np.concatenate([e_train, p_train])
X_val = np.concatenate([e_val, p_val])
X_test = np.concatenate([e_test, p_test])

In [ ]:
print((np.asarray(e_train)).shape)
print((np.asarray(p_train)).shape)
print((np.asarray(e_val)).shape)
print((np.asarray(p_val)).shape)
print((np.asarray(e_test)).shape)
print((np.asarray(p_test)).shape)

print((np.asarray(X_train)).shape)
print((np.asarray(X_val)).shape)
print((np.asarray(X_test)).shape)

(199200, 32, 32, 2)
(199200, 32, 32, 2)
(24900, 32, 32, 2)
(24900, 32, 32, 2)
(24900, 32, 32, 2)
(24900, 32, 32, 2)
(398400, 32, 32, 2)
(49800, 32, 32, 2)
(49800, 32, 32, 2)


In [ ]:
ey_train = []
py_train = []
ey_val = []
py_val = []
ey_test = []
py_test = []
for i in range(0,199200):
  ey_train.append(e_y[i])
  py_train.append(p_y[i])

for j in range(199200, 224100):
  ey_val.append(e_y[j])
  py_val.append(p_y[j])

for k in range(224100, 249000):
  ey_test.append(e_y[k])
  py_test.append(p_y[k])

In [ ]:
Y_train = np.concatenate([ey_train, py_train])
Y_val = np.concatenate([ey_val, py_val])
Y_test = np.concatenate([ey_test, py_test])

In [ ]:
print((np.asarray(ey_train)).shape)
print((np.asarray(py_train)).shape)
print((np.asarray(ey_val)).shape)
print((np.asarray(py_val)).shape)
print((np.asarray(ey_test)).shape)
print((np.asarray(py_test)).shape)

print((np.asarray(Y_train)).shape)
print((np.asarray(Y_val)).shape)
print((np.asarray(Y_test)).shape)

(199200,)
(199200,)
(24900,)
(24900,)
(24900,)
(24900,)
(398400,)
(49800,)
(49800,)


In [1]:
import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt
from time import time
from torchvision import datasets, transforms
from torch import nn, optim
from sklearn.metrics import accuracy_score

In [ ]:
input_size = 2048
hidden_sizes = [128, 64]
output_size = 2

model = nn.Sequential(nn.Linear(input_size, hidden_sizes[0]),
                      nn.ReLU(),
                      nn.Linear(hidden_sizes[0], hidden_sizes[1]),
                      nn.ReLU(),
                      nn.Linear(hidden_sizes[1], output_size),
                      nn.LogSoftmax(dim=1))
print(model)

Sequential(
  (0): Linear(in_features=2048, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=2, bias=True)
  (5): LogSoftmax(dim=1)
)


In [2]:
model = nn.Sequential(nn.Conv2d(2, 256, (3,3), 1, 1),
                      nn.ReLU(),
                      nn.BatchNorm2d(256,momentum=0.8),
                      nn.Conv2d(256, 256, (3,3), 1, 1),
                      nn.ReLU(),
                      nn.BatchNorm2d(256, momentum=0.8),
                      nn.Dropout(0.3),
                      nn.Conv2d(256, 128, (3,3), 1, 1),
                      nn.ReLU(),
                      nn.BatchNorm2d(128,momentum=0.8),
                      nn.Conv2d(128, 64, (3,3), 1, 1),
                      nn.ReLU(),
                      nn.BatchNorm2d(64, momentum=0.8),
                      nn.Dropout(0.5),
                      nn.Conv2d(64, 3, (3,3), 1, 1),
                      nn.ReLU(),
                      nn.Flatten(),
                      nn.Linear(3,1),
                      nn.Sigmoid())

print(model)

Sequential(
  (0): Conv2d(2, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU()
  (2): BatchNorm2d(256, eps=1e-05, momentum=0.8, affine=True, track_running_stats=True)
  (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): ReLU()
  (5): BatchNorm2d(256, eps=1e-05, momentum=0.8, affine=True, track_running_stats=True)
  (6): Dropout(p=0.3, inplace=False)
  (7): Conv2d(256, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU()
  (9): BatchNorm2d(128, eps=1e-05, momentum=0.8, affine=True, track_running_stats=True)
  (10): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU()
  (12): BatchNorm2d(64, eps=1e-05, momentum=0.8, affine=True, track_running_stats=True)
  (13): Dropout(p=0.5, inplace=False)
  (14): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU()
  (16): Flatten(start_dim=1, end_dim=-1)
  (17): Linear(in_features=3, out_features=1, bias=True)
  (18): Sigmoid()
)


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model.to(device)

cpu


Sequential(
  (0): Linear(in_features=2048, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=2, bias=True)
  (5): LogSoftmax(dim=1)
)

In [ ]:
y_train = []
for i in range(199200):
  y_train.append(1)

for i in range(199200):
  y_train.append(0)

In [ ]:
y_train = np.asarray(y_train)

In [ ]:
print(X_train.shape)
print(y_train.shape)

(398400, 32, 32, 2)
(398400,)


In [ ]:
trainloader1 = torch.utils.data.DataLoader(X_train, batch_size=1, shuffle=False)
trainloader2 = torch.utils.data.DataLoader(y_train, batch_size=1, shuffle=False)

In [ ]:
print(trainloader1)
print(trainloader2)

In [ ]:
criterion = nn.NLLLoss()
images = next(iter(trainloader1))
labels = next(iter(trainloader2))
images = images.view(images.shape[0], -1)

logps = model(images) #log probabilities
loss = criterion(logps, labels) #calculate the NLL loss

In [ ]:
print(images[0])

tensor([0., 0., 0.,  ..., 0., 0., 0.])


In [ ]:
print(labels)

tensor([1])


In [ ]:
print('Before backward pass: \n', model[0].weight.grad)
loss.backward()
print('After backward pass: \n', model[0].weight.grad)

Before backward pass: 
 None
After backward pass: 
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [ ]:
optimizer = optim.SGD(model.parameters(), lr=0.003, momentum=0.9)
time0 = time()
epochs = 150
num_batches = 1
correct_count, all_count = 0, 0
for e in range(epochs):
    running_loss = 0
    # for (images, labels) in (trainloader1, trainloader2):
    for idx in range(num_batches):
        # Flatten MNIST images into a 784 long vector
        # images = images.view(images.shape[0], -1)
        # correct = 0
        # total = 0
        images = next(iter(trainloader1))
        labels = next(iter(trainloader2))
        # print(labels)
        # print(images1.shape)
        images = images.view(images.shape[0], -1)
        # Training pass
        optimizer.zero_grad()
        
        output = model(images)
        # print(output)
        loss = criterion(output, labels)
        
        #This is where the model learns by backpropagating
        loss.backward()
        
        #And optimizes its weights here
        optimizer.step()
        
        running_loss += loss.item()
    else:
        print("Epoch {} - Training loss: {} ".format(e, running_loss/len(trainloader2)))
# print("\nTraining Time (in minutes) =",(time()-time0)/60)

Epoch 0 - Training loss: 1.175616938905065e-06 
Epoch 1 - Training loss: 1.1722988123635212e-06 
Epoch 2 - Training loss: 1.166053340736642e-06 
Epoch 3 - Training loss: 1.157260907582011e-06 
Epoch 4 - Training loss: 1.146136502544564e-06 
Epoch 5 - Training loss: 1.13303754403888e-06 
Epoch 6 - Training loss: 1.1181509698251165e-06 
Epoch 7 - Training loss: 1.1016997736859992e-06 
Epoch 8 - Training loss: 1.083924004950198e-06 
Epoch 9 - Training loss: 1.0650903435356645e-06 
Epoch 10 - Training loss: 1.0452670116261785e-06 
Epoch 11 - Training loss: 1.024611099776494e-06 
Epoch 12 - Training loss: 1.0033537555171783e-06 
Epoch 13 - Training loss: 9.816279073795641e-07 
Epoch 14 - Training loss: 9.595316247528336e-07 
Epoch 15 - Training loss: 9.371353739715485e-07 
Epoch 16 - Training loss: 9.145388701354644e-07 
Epoch 17 - Training loss: 8.918493836519709e-07 
Epoch 18 - Training loss: 8.692955186807487e-07 
Epoch 19 - Training loss: 8.46831644155893e-07 
Epoch 20 - Training loss: 

In [ ]:
y_val = []
for i in range(24900):
  y_val.append(1)

for i in range(24900):
  y_val.append(0)

In [ ]:
y_val = np.asarray(y_val)

In [ ]:
print(X_val.shape)
print(y_val.shape)

(49800, 32, 32, 2)
(49800,)


In [ ]:
valloader1 = torch.utils.data.DataLoader(X_val, batch_size=1, shuffle=False)
valloader2 = torch.utils.data.DataLoader(y_val, batch_size=1, shuffle=False)

In [ ]:
correct_count, all_count = 0, 0
# for images,labels in valloader:
for idx in range(49800):
  images = next(iter(valloader1))
  labels = next(iter(valloader2))
  for i in range(len(labels)):
    img = images[i].view(1, 2048)
    # Turn off gradients to speed up this part
    with torch.no_grad():
        logps = model(img)

    # Output of the network are log-probabilities, need to take exponential for probabilities
    ps = torch.exp(logps)
    probab = list(ps.numpy()[0])
    pred_label = probab.index(max(probab))
    true_label = labels.numpy()[i]
    if(true_label == pred_label):
      correct_count += 1
    all_count += 1

print("Number Of Images Tested =", all_count)
print("\nModel Accuracy =", (correct_count/all_count))

Number Of Images Tested = 49800

Model Accuracy = 1.0


In [ ]:
print(Y_val)

[1. 1. 1. ... 0. 0. 0.]
